import { Coffee, Database, Server, FileCode, Code2, Network, Cloud } from "lucide-react";
import {
  SiSpringboot,
  SiSpring,
  SiHibernate,
  SiHtml5,
  SiCss,
  SiJavascript,
  SiBootstrap,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiGit,
  SiGithub,
  SiPostman,
  SiEclipseide,
  SiIntellijidea,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiFramer,
  SiGsap,
  SiJsonwebtokens,
  SiSwagger,
  SiDocker,
  SiApachekafka,
  SiKubernetes,
} from "react-icons/si";

type SkillIconComponent = React.ComponentType<{
  size?: string | number;
}>;

const iconMap: Record<string, SkillIconComponent> = {
  Java: Coffee,
  SQL: Database,
  JavaScript: SiJavascript,
  "Spring Boot": SiSpringboot,
  "Spring MVC": SiSpring,
  "Hibernate ORM": SiHibernate,
  "Spring Data JPA": SiSpring,
  Servlets: Server,
  JSP: FileCode,
  React: SiReact,
  "Next.js": SiNextdotjs,
  "Tailwind CSS": SiTailwindcss,
  "Framer Motion": SiFramer,
  GSAP: SiGsap,
  HTML5: SiHtml5,
  CSS3: SiCss,
  Bootstrap: SiBootstrap,
  MySQL: SiMysql,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  Git: SiGit,
  GitHub: SiGithub,
  Postman: SiPostman,
  "IntelliJ IDEA": SiIntellijidea,
  "Eclipse IDE": SiEclipseide,
  "VS Code": Code2,
  "Hibernate / JPA": SiHibernate,
  "Servlet & JSP": Server,
  "REST APIs": Network,
  "Git & GitHub": SiGithub,
  JDBC: Database,
  "Spring Security": SiSpring,
  "Swagger / OpenAPI": SiSwagger,
  "System Design": Network,
  Maven: Code2,
  "Node.js": Code2,
  "Express.js": Code2,
  TypeScript: Code2,
  JWT: SiJsonwebtokens,
  Swagger: SiSwagger,
  Microservices: Network,
  Docker: SiDocker,
  Kafka: SiApachekafka,
  AWS: Cloud,
  Kubernetes: SiKubernetes,
};

export default function SkillIcon({ name, size = 18 }: { name: string; size?: number }) {
  const Icon = iconMap[name] ?? Code2;
  return <Icon size={size} />;
}
